name: infrafair-doc
channels:
- conda-forge
dependencies:
- python>=3.8,<3.10
- pip
- python
- six
- numpy>=1.23.0,<1.26.4
- pandas=1.3.4
- xarray
- netcdf4
- pytables
- matplotlib>=3.5.0
- pandoc
- linopy>=0.2
- openpyxl>=3.0.0

- pip:
  - .
  - sphinx<6
  - sphinx-book-theme

